import Head from 'next/head';
import { data } from '../data';
import React from 'react';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="org-chart-wrapper">
        {data.map((row: any, rowIndex: any) => {
          return (
            <div className="row-wrapper" key={rowIndex}>
              {row.map((column: any, columnIndex: any) => (
                <React.Fragment key={columnIndex}>
                  {rowIndex === 0 && columnIndex === 0 ? (
                    <>
                      {Array(20)
                        .fill('')
                        .map((_, i) => (
                          <div className={`column-wrapper left-line`} key={i}>
                            <span className="strikethrough"></span>
                            <span className="left-line"></span>
                          </div>
                        ))}
                    </>
                  ) : null}
                  <div
                    className={`column-wrapper box
                    ${rowIndex === 0 && columnIndex === 0 ? 'main bottom-line' : ''} 
                    ${rowIndex > 1 && columnIndex === 0 ? `main ${row.length > 2 ? 'top-line top-right-line left-line' : 'left-line'}` : ''} 
                    ${!(rowIndex === 0 && columnIndex === 0) && row.length > 2 && `top-line`} 
                    ${row.at(-1).id !== column?.id && !(rowIndex === 0 && columnIndex === 0) && row.length > 2 && 'top-right-line'}
                    ${(rowIndex === 0 && columnIndex === 0) || (rowIndex > 1 && row.length < 3 && columnIndex === 0) ? 'right-line' : ''}
                    `}
                  >
                    <h3>{column.title}</h3>
                    <span className="strikethrough"></span>
                    <span className="top-line"></span>
                    <span className="bottom-line"></span>
                    <span className="left-line"></span>
                    <span className="right-line"></span>
                    <span className="top-right-line"></span>
                  </div>
                  <div className="column-wrapper visually-hidden"></div>
                  {column.hasOwnProperty('children') &&
                    column.children.map((child: any, i: any) => {
                      return (
                        <React.Fragment key={i}>
                          <div
                            className={`column-wrapper column-child top-line top-left-line box
                            ${row.length > 2 ? 'top-right-line' : ''} 
                            ${i === 0 ? 'first-child' : ''}`}
                          >
                            <h3>{child.title}</h3>
                            <span className="strikethrough"></span>
                            <span className="top-line"></span>
                            <span className="bottom-line"></span>
                            <span className="left-line"></span>
                            <span className="right-line"></span>
                            <span className="top-right-line"></span>
                            <span className="top-left-line"></span>
                          </div>
                          <div className={`column-wrapper visually-hidden`}></div>
                        </React.Fragment>
                      );
                    })}
                </React.Fragment>
              ))}
              <span className="row-line"></span>
            </div>
          );
        })}
      </div>
    </>
  );
}
