import Head from 'next/head';
import { data } from '../data';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="org-chart-wrapper">
        {data.map((row: any, i: any) => {
          return (
            <div className="row-wrapper" key={i}>
              {row.map((column: any, i: any) => (
                <>
                  <div
                    className={`column-wrapper ${column.className.join(' ')} ${column.hasInfo ? 'box' : ''} ${
                      column.isMain ? 'main' : ''
                    }`}
                    key={i}
                  >
                    <h3>{column.title}</h3>
                    <span className="strikethrough"></span>
                    <span className="top-line"></span>
                    <span className="bottom-line"></span>
                    <span className="left-line"></span>
                    <span className="right-line"></span>
                    <span className="top-right-line"></span>
                  </div>
                  {column.hasOwnProperty('children') &&
                    column.children.map((child: any, i: any) => {
                      return (
                        <div
                          className={`column-wrapper column-child ${child.className.join(' ')} ${
                            child.hasInfo ? 'box' : ''
                          } ${child.isMain ? 'main' : ''} ${i === 1 ? 'first-child' : ''}`}
                          key={i}
                        >
                          <h3>{child.title}</h3>
                          <span className="strikethrough"></span>
                          <span className="top-line"></span>
                          <span className="bottom-line"></span>
                          <span className="left-line"></span>
                          <span className="right-line"></span>
                          <span className="top-right-line"></span>
                          <span className="top-left-line"></span>
                        </div>
                      );
                    })}
                </>
              ))}
              <span className="row-line"></span>
            </div>
          );
        })}
      </div>
    </>
  );
}
